project/__init__.py
from flask import Flask, request, session, render_template
from project.models import db
from flask_session import Session
from flask_wtf.csrf import CSRFProtect, generate_csrf  # csrf配置(防止csrf攻击)
import logging
from logging.handlers import RotatingFileHandler
import setting
from redis import Redis

redis_connect = None


def create_app(config_name):
    app = Flask(__name__)
    # 配置设置
    config = setting.config_dict.get(config_name)
    app.config.from_object(config)
    # 定义redis连接
    global redis_connect
    redis_connect = Redis(host=config.REDIS_HOST, port=config.REDIS_PORT, password=config.REDIS_PASSWORD)
    # 日志
    log_file(config.LEVEL_NAME)
    # session
    Session(app)
    # csrf防护
    CSRFProtect(app)
    # 数据库
    db.init_app(app)
    # 自定义过滤器注册（参数1：函数名，参数2：过滤器名字）
    from project.template_tag import class_filter, transfer_time, to_category,digest_format,flask_url_deal
    app.add_template_filter(class_filter, "my_tag")
    app.add_template_filter(transfer_time, "transfer_time")
    app.add_template_filter(to_category, "to_category")
    app.add_template_filter(digest_format, "digest_format")
    app.add_template_filter(flask_url_deal, "flask_url_deal")
    # 蓝图注册
    from project.views import account, news_category, news_details, user,admin
    app.register_blueprint(account.ac)
    app.register_blueprint(news_category.nc)
    app.register_blueprint(news_details.details)
    app.register_blueprint(user.user)
    app.register_blueprint(admin.admin)

    @app.before_request
    def before_request():
        request.user = None
        request.category = None
        mobile = session.get("user")
        if not mobile:
            mobile = session.get("admin")
        user_obj = models.User.query.filter(models.User.mobile == mobile).first()
        category_obj = models.Category.query.all()
        if category_obj:
            request.category = category_obj
        if mobile and user_obj:
            request.user = user_obj
            return
        return

    @app.after_request
    def after_request(response):
        csrf_token = generate_csrf()
        response.set_cookie('csrf_token', csrf_token)
        return response

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("404.html"), 404

    return app


def log_file(LEVEL_NAME):
    logging.basicConfig(level=LEVEL_NAME)
    file_handler = RotatingFileHandler('logs/log', maxBytes=1024*1024*10, backupCount=100)
    formatter = logging.Formatter(fmt="%(asctime)s->%(levelname)s->%(filename)s第%(lineno)d行: %(message)s")
    file_handler.setFormatter(formatter)
    logging.getLogger().addHandler(file_handler)

project/views/account.py
import datetime
import random
from flask import Blueprint, render_template, session, request, jsonify, url_for, redirect
from flask import current_app, send_file

from project.script.get_param_list import flask_get_per_param_list
from project.script.pic_code import check_code
from io import BytesIO
from project import my_forms
from project import models
from project import redis_connect
from project.models import db
import logging

# from flask_wtf.csrf import generate_csrf
# from sqlalchemy import or_, and_, text

ac = Blueprint('ac', __name__, template_folder='news/templates', static_folder='news/static')


@ac.route('/')
def redirect_to_index():
    # status_list = flask_get_per_param_list(request.url,"status")
    # category_id_list = flask_get_per_param_list(request.url,"category_id")
    # # # 允许的筛选条件
    # # allow_filter_name = ['status', 'category_id']
    # if status_list and category_id_list:
    #     print("all")
    #     objs=models.News.query.filter(models.News.status.in_(status_list),models.News.category_id.in_(category_id_list)).all()
    # elif status_list and not category_id_list:
    #     print("status")
    #     objs = models.News.query.filter(models.News.status.in_(status_list)).all()
    # elif not status_list and category_id_list:
    #     print("category")
    #     objs = models.News.query.filter(models.News.category_id.in_(category_id_list)).all()
    # else:
    #     print("none")
    #     objs=models.News.query.all()
    # print(status_list,category_id_list,objs[0:5])
    # return "666"
    return redirect(url_for("ac.index"))


@ac.route('/index', methods=['GET', 'POST'], endpoint='index')
def index():
    # 查询点击量多的10条资讯
    hot_news = None
    latest_news = None
    data = {}
    try:
        hot_news = models.News.query.order_by(models.News.clicks.desc()).limit(10).all()
        suggestions = models.News.query.order_by(models.News.collected_counts.desc()).limit(10).all()
        # latest_notice = models.Notice.query.order_by(models.Notice.update_time.desc()).first()
    except Exception as e:
        logging.error(e)
        data['news-error'] = "无法访问数据库"
        hot_news = []
        suggestions = []
        # latest_notice = None
    data['hot_news'] = hot_news
    data['suggestions'] = suggestions
    # data['latest_notice'] = latest_notice
    return render_template('index.html', request=request, data=data)


@ac.route('/favicon.ico', methods=['GET', 'POST'], endpoint='logo')
def logo():
    return current_app.send_static_file('images/02.ico')


@ac.route('/login', methods=['GET', 'POST'], endpoint='login')
def login():
    if request.method == 'GET':
        return render_template('login.html', request=request)
    # 获取请求参数
    mobile = request.form.get('mobile')
    password = request.form.get('password')
    pic_code = request.form.get('pic_code')
    img_id = request.form.get('img_id')
    # 校验图片验证码
    redis_code = str(redis_connect.get(img_id), encoding='utf-8')
    if str(pic_code).upper() != str(redis_code).upper():
        return jsonify(status=False, error=[{"for_pic_code": "验证码错误"}])
    try:
        user_obj = models.User.query.filter(models.User.mobile == mobile).first()
    except Exception as e:
        logging.info(e)
        return jsonify(status=False, error=[{"db_error": "数据库请求错误"}])
    if not user_obj:
        logging.info(mobile + "账号错误或还没有注册")
        return jsonify(status=False, error=[{"for_mobile": "账号错误或还没有注册"}])
    if not user_obj.check_password(password):
        logging.info(mobile + "密码错误")
        return jsonify(status=False, error=[{"for_password": "密码错误"}])
    session['user_id'] = user_obj.id
    session['user'] = mobile
    try:
        user_obj.last_login = datetime.datetime.now()
        db.session.commit()
    except Exception as e:
        logging.info(e)
    return jsonify(status=True, data='/')


@ac.route('/logout', methods=['GET'], endpoint='logout')
def logout():
    session.pop("user_id", None)
    session.pop("user", None)
    return redirect('/login')


@ac.route('/register', methods=['GET', 'POST'], endpoint='register')
def register():
    if request.method == 'GET':
        form = my_forms.RegisterForm()
        return render_template('register.html', form=form, request=request)
    else:
        form = my_forms.RegisterForm(formdata=request.form)
        logging.info(request.form)
        if form.validate():
            mobile = request.form.get("mobile")
            password_hash = request.form.get("password_hash")
            post_code = request.form.get("sms_code")
            sms_code = str(redis_connect.get(mobile), encoding='utf-8')
            if not sms_code:
                logging.error(mobile + "短信验证码过期")
                return jsonify({'status': False, 'sms_error': "短信验证码过期"})
            if str(post_code) != sms_code:
                logging.error(mobile + "短信验证码错误")
                return jsonify({'status': False, 'sms_error': "短信验证码错误"})

            user_obj = models.User()
            user_obj.nick_name = mobile
            user_obj.password = password_hash
            user_obj.mobile = mobile
            user_obj.signature = "该用户很懒，什么都没写..."
            try:
                db.session.add(user_obj)
                db.session.commit()
            except Exception as e:
                logging.info(e)
                return jsonify({'status': False, 'db_error': "注册失败"})
            redis_connect.delete(mobile)
            return jsonify(status=True, data="/login")
        else:
            logging.info(form.errors)
            return jsonify({'status': False, 'error': form.errors})


@ac.route('/code', endpoint='code')
def code():
    try:
        img_id = request.args.get('img_id')
        img_obj, code = check_code('project/script/font_file/Monaco.ttf')
        redis_connect.set(name=img_id, value=code, ex=300)
        stream = BytesIO()
        img_obj.save(stream, 'png')
    except Exception as e:
        logging.error(e)
        return jsonify(staus=False, error=e)
    return stream.getvalue()


@ac.route('/send/sms', endpoint='send_sms')
def send_sms():
    mobile = request.args.get('mobile')
    img_code = request.args.get('img_code')
    img_id = request.args.get('img_id')
    pic_code = str(redis_connect.get(img_id), encoding='utf-8')
    # 生成验证码并存储到Redis
    sms_code = random.randrange(100000, 999999)
    redis_connect.set(mobile, sms_code)
    # 校验手机号格式、是否注册过
    import re
    pattern = r'^1[3456789]\d{9}$'
    res = re.search(pattern, str(mobile))
    if not res:
        logging.info("手机格式错误")
        return jsonify(status=False, error="手机格式错误")
    user_obj = models.User.query.filter(models.User.mobile == mobile).first()
    logging.info(user_obj)
    if user_obj:
        return jsonify(status=False, error="该手机已经注册过了")
    # 校验图片验证码
    if str(img_code).upper() != pic_code.upper():
        logging.info("图片验证码错误")
        return jsonify(status=False, error="图片验证码错误")
    # return jsonify(status=True)
    return jsonify(status=True,code=sms_code)

project/views/admin/__init__.py
from flask import Blueprint

admin = Blueprint("admin", __name__, url_prefix="/admin")

from . import views

project/views/news_category.py
from flask import Blueprint, render_template, session, request, jsonify, url_for, redirect
from project import models
import logging
from flask_wtf.csrf import generate_csrf

nc = Blueprint("nc", __name__)


@nc.route('/get_news')
def news():
    # 获取参数
    category_id = request.args.get('cid', "1")
    page = request.args.get('page', "1")
    per_page = request.args.get('per_page', "10")
    # 参数类型转换
    try:
        page = int(page)
        per_page = int(per_page)
    except Exception as e:
        logging.error(e)
        page = 1
        per_page = 10
    try:
        if category_id == "1":
            news_obj = models.News.query.filter(models.News.status == 1).order_by(
                models.News.create_time.desc())
        else:
            news_obj = models.News.query.filter(models.News.category_id == category_id,
                                                models.News.status == 1).order_by(
                models.News.create_time.desc())
        paginate_obj = news_obj.paginate(page, per_page, False)
    except Exception as e:
        logging.error(e)
        return jsonify(status=False, error="请求错误：%s" % e)
    # 获取分页对象的属性
    total_page = paginate_obj.pages
    current_page = paginate_obj.page
    all_objs = paginate_obj.items
    logging.info("分类ID:" + str(category_id) + ";数据集:" + str(news_obj.all()))
    news_list = []
    for item in all_objs:
        news_list.append(item.to_dict())
    if news_list.__len__() == 0:
        error_url = url_for('static', filename='images/loading.gif', _external=True)
        logging.info(error_url)
        return jsonify(status=False, error=error_url)
    return jsonify(status=True, totalPage=total_page, newsList=news_list)


@nc.route('/notice/list', endpoint="notice_list")
def notice_list():
    data = {}
    try:
        notice_list = models.Notice.query.order_by(models.Notice.update_time.desc()).all()
        hot_news = models.News.query.order_by(models.News.clicks.desc()).limit(10).all()
        suggestions = models.News.query.order_by(models.News.collected_counts.desc()).limit(10).all()
        data['hot_news'] = hot_news
        data['suggestions'] = suggestions
    except Exception as e:
        notice_list = []
        logging.error(e)
    res_list = []
    for item in notice_list:
        res_list.append(item.to_dict())
    data["notice_list"] = res_list
    return render_template("notice_list.html", data=data)


@nc.route('/notice/<int:nid>', endpoint="notice_scan")
def notice_scan(nid):
    data = {}
    url = url_for("nc.notice_list")
    try:
        notice_obj = models.Notice.query.get(int(nid))
        if not notice_obj:
            return redirect(url)
        else:
            notice_obj=notice_obj.to_dict()
        hot_news = models.News.query.order_by(models.News.clicks.desc()).limit(10).all()
        suggestions = models.News.query.order_by(models.News.collected_counts.desc()).limit(10).all()
        data['hot_news'] = hot_news
        data['suggestions'] = suggestions
    except Exception as e:
        logging.error(e)
        return redirect(url)
    data["notice_obj"] = notice_obj
    return render_template("notice_scan.html", data=data)

project/views/news_details/__init__.py
from flask import Blueprint

details=Blueprint("detail",__name__,url_prefix="/news")

from . import views

project/views/user/__init__.py
from flask import Blueprint

user = Blueprint("user", __name__, url_prefix="/user")

from . import views

project/templates/login.html
{% extends 'base.html' %}
{% block title %}佳猫资讯-登陆{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login.css',_external=True) }}">
{% endblock %}
{% block content %}
    <div class="container-fluid" style="margin-top: 10px;">
        <div id="login-div" style="border-radius: 5px;border: 1px solid #00a8c6;margin: 10px auto;padding: 10px 10px;">
            <p style="font-size: 28px;text-align: center;color: #2b669a;">登陆</p>
            <form id="loginForm" method="POST" novalidate>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input type="hidden" id="img_id" name="img_id" value="">
                <div class="form-group" style="margin-bottom: 8px;">
                    <label for="mobile">手机号</label><span id="for_mobile" class="error" style="color: red;"></span>
                    <input type="text" name="mobile" id="mobile" class="form-control" placeholder="请输入手机号">
                </div>
                <div class="form-group" style="margin-bottom: 8px;">
                    <label for="password">密码</label><span id="for_password" class="error" style="color: red;"></span>
                    <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码">
                </div>
                <div class="form-group">
                    <label for="pic_code">验证码</label><span id="for_pic_code" class="error" style="color: red;"></span>
                    <div class="row">
                        <div class="col-md-6" style="margin-top: 5px;">
                            <input type="text" name="pic_code" id="pic_code" class="form-control" placeholder="请输入验证码"
                                   autocomplete="off">
                        </div>
                        <div class="col-md-6">
                            <div id="code-div">
                                <img id="imgCode" src="" alt="验证码" title="刷新" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <a id="btnLogin" class="form-control btn btn-primary">
                    登录
                </a>
                <div class="form-group register-to-login" style="text-align: center;margin-top: 10px;">
                    <span>没有账号？立即</span><a href="/register">注册</a>
                </div>
                <div id="db_error" class="error" style="color: red;height: 8px;"></div>
            </form>
        </div>
    </div>
    <div style="height: 50px;"></div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            initImgCode();
            newImgCode();
            loginBtnClick();
        });

        function generateUuid() {
            return Math.random().toString(36).substr(2);
        }

        function initImgCode() {
            let $imgCodeBtn = $("#imgCode");
            var randomStr = generateUuid();
            $imgCodeBtn.attr('src', "/code?img_id=" + randomStr);
            $imgCodeBtn.attr('img_id', randomStr);
            $("#img_id").attr('value', randomStr);
            //console.log()
        }

        function newImgCode() {
            let $imgCodeBtn = $("#imgCode");
            $imgCodeBtn.click(function () {
                var newRandomStr = Math.random().toString(36).substr(2);
                $(this).attr('src', "/code?img_id=" + newRandomStr);
                $imgCodeBtn.attr('img_id', newRandomStr);
                $("#img_id").attr('value', newRandomStr);
            })
        }

        //显示错误提示框
        function showErrorDiv(res) {
            let $msgDiv = $(".message-tips");
            $msgDiv.removeClass("hidden");
            $("#msg").text(res.error);
            $msgDiv.width();
            divJustifyCenter($msgDiv.width());
            let aTimeOut = setTimeout(function () {
                $("#msg").empty();
                $msgDiv.addClass("hidden");
                $msgDiv.css("left", "");
                clearTimeout(aTimeOut);
            }, 5000)
        }

        //错误提示框居中
        function divJustifyCenter(divWidth) {
            let pageWidth = $(window).width();
            let $div = $(".message-tips");
            let toLeft = (pageWidth - divWidth) / 2;
            $div.css("left", toLeft);
        }

        function loginBtnClick() {
            $("#btnLogin").click(function () {
                const $mobile = $("#mobile").val();
                const $password = $("#password").val();
                const $pic_code = $("#pic_code").val();
                let flags = 0;
                if ($mobile.length === 0) {
                    $("#for_mobile").text("手机号输入不能为空");
                    flags = 1;
                    let timeCount1 = setTimeout(function () {
                        $('.error').empty();
                        clearTimeout(timeCount1)
                    }, 5000)
                }
                if ($password.length === 0) {
                    $("#for_password").text("密码输入不能为空");
                    flags = 1;
                    let timeCount1 = setTimeout(function () {
                        $('.error').empty();
                        clearTimeout(timeCount1)
                    }, 5000)
                }
                if ($pic_code.length === 0) {
                    $("#for_pic_code").text("验证码输入不能为空");
                    flags = 1;
                    let timeCount1 = setTimeout(function () {
                        $('.error').empty();
                        clearTimeout(timeCount1)
                    }, 5000)
                }
                if (flags === 0) {
                    const LoginUrl = "/login";
                    $.ajax({
                        url: LoginUrl,
                        data: $("#loginForm").serializeArray(),
                        type: 'POST',
                        dataType: 'JSON',
                        success: function (res) {
                            if (res.status) {//成功
                                location.href = res.data;
                            } else {//失败
                                initImgCode();
                                $.each(res.error, function (key, value) {
                                    console.log(key, value);
                                    $.each(value,function (k,v) {
                                        $("#" + k).text(v);
                                    let timeCount = setTimeout(function () {
                                        $('.error').empty();
                                        clearTimeout(timeCount)
                                    }, 5000)
                                    });
                                });
                            }
                        }
                    })
                }
            });
        }
    </script>
{% endblock %}
{% block news_category %}

{% endblock %}

project/templates/notice_list.html
{% extends 'detail_base.html' %}
{% block title %}
    公告-佳猫新闻
{% endblock %}
{% block css %}

{% endblock %}
{% block main %}
    <div class="container-fluid" style="">
        <div class="col-lg-3 hidden-sm hidden-xs">
            <div class="panel panel-info">
                <div class="panel-heading" style="text-align: center;">推荐阅读TOP10</div>
                <ul class="list-group" id="hot_news">
                    {% for new_obj in data.suggestions %}
                        <li class="list-group-item">
                            <div class="{{ loop.index | my_tag }}" style="display: inline">{{ loop.index }}</div>
                            <div style="display: inline">
                                <a href="{{ url_for("detail.detail",nid=new_obj.id) }}">{{ new_obj.title }}</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="notice-container col-lg-6 container-fluid" style="background:white;">
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>标题</th>
                        <th>发布时间</th>
                        <th>更新时间</th>
                        <th>发布者</th>
                    </tr>
                    {% for obj in data.notice_list %}
                        <tr>
                            <td><a href="{{ url_for("nc.notice_scan",nid=obj.id) }}">{{ obj.title }}</a></td>
                            <td>{{ obj.create_time }}</td>
                            <td>{{ obj.update_time }}</td>
                            <td>{{ obj.admin.nick_name }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="col-lg-3 hidden-sm hidden-xs">
            <div class="panel panel-info">
                <div class="panel-heading" style="text-align: center;">热门新闻TOP10</div>
                <ul class="list-group" id="hot_news">
                    {% for new_obj in data.hot_news %}
                        <li class="list-group-item">
                            <div class="{{ loop.index | my_tag }}" style="display: inline">{{ loop.index }}</div>
                            <div style="display: inline">
                                <a href="{{ url_for("detail.detail",nid=new_obj.id) }}">{{ new_obj.title }}</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

project/templates/second_news.html
{% extends 'index.html' %}
{% block css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/latest_news.css',_external=True) }}">
{% endblock %}
{% block news %}
    {% for item in data.latest_news %}
        <div class="new-item">
            <div class="clearfix row row-no-gutter" style="margin-top: 5px;margin-left: 3px;">
                <div class="col-xs-4 col-md-2 col-lg-2">
                    {#                {{ item.index_image_url }}#}
                    <img class="img" src="{{ url_for('static',filename='images/default.jpg',_external=True) }}"
                         alt="00">
                </div>
                <div class="col-xs-8 col-md-10 col-lg-10">
                    <h4 class="title"><a href="">{{ item.title }}</a></h4>
                    <p class="hidden-xs hidden-sm">
                        {{ item.digest }}
                    </p>
                </div>
            </div>
            <div class="mini-show-div row clearfix" style="margin-top: 5px;margin-left: 3px;">
                <p class="pull-right col-xs-12 col-md-12 col-lg-12">
                    <span class="mini-show">{{ item.user_id.nick_name }}</span>
                    <span class="mini-show">发布于{{ item.create_time | transfer_time }}</span>
                    <span class="mini-show left-10">来源于:{{ item.source }}</span>
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

project/templates/user.html
{% extends 'detail_base.html' %}
{% block title %}
    用户中心-佳猫资讯
{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for("static",filename="css/user.css") }}">
    <style>
        a:hover {
            text-decoration: none;
        }

        .select a {
            color: #2b669a !important;
        }

        .user-pic {
            width: 120px;
            height: 120px;
            position: absolute;
            left: 10px;
            top: -50px;
        }

        .user-pic img {
            width: 100px;
            height: 100px;
            border-radius: 50px;
        }

        .user-menu {
            max-height: 600px;
            background: #fff;
            margin: 60px 0 0 0;
            position: relative;
        }

        .user-name {
            text-align: center;
            margin-top: 60px;
            font-size: 18px;
            word-break: break-all;
            word-wrap: break-word;
        }

        .user-choice {
            margin-top: 15px;
        }

        .user-choice li {
            text-align: center;
        }

        .user-choice li a {
            color: black;
            cursor: pointer;
        }

        .user-choice li a:hover {
            cursor: pointer;
        }

        .info-show {
            background: white;
            min-height: 500px;
        }

        @media (max-width: 361px) {
            .user-pic {
                width: 80px;
                height: 80px;
                position: absolute;
                top: -30px;
            }

            .user-name span {
                font-size: 14px;
            }

            .user-pic img {
                width: 60px;
                height: 60px;
                border-radius: 30px;
            }

            .user-menu {
                max-height: 1200px;
                margin: 60px 0 0 0;
            }
        }

        @media (min-width: 768px) {
            .menu-choice {
                font-size: 16px !important;
            }
        }
    </style>
{% endblock %}
{% block main %}
    <div class="container-fluid padding-0">
        <div class="col-xs-4 col-sm-4 col-md-3 col-lg-3 user-menu">
            <div class="user-pic text-center">
                <a href="{{ request.user.avatar_url }}" target="_self">
                    <img src="{{ request.user.avatar_url }}" alt="用户头像">
                </a>
            </div>
            <div class="text-center user-name"><span>{{ request.user.nick_name }}</span></div>
            <ul class="list-group user-choice">
                <li class="select list-group-item">
                    <a class="menu-choice" href="{{ url_for("user.base_info") }}" target="main_frame">基本资料</a>
                </li>
                <li class="list-group-item">
                    <a class="menu-choice" href="{{ url_for("user.avatar") }}" target="main_frame">头像设置</a>
                </li>
                <li class="list-group-item">
                    <a class="menu-choice" href="{{ url_for("user.password") }}" target="main_frame">密码修改</a>
                </li>
                <li class="list-group-item">
                    <a class="menu-choice" href="{{ url_for("user.my_collections") }}" target="main_frame">我的收藏</a>
                </li>
                <li class="list-group-item">
                    <a class="menu-choice" href="{{ url_for("user.my_idols") }}" target="main_frame">我的关注</a>
                </li>
                {% if request.user.is_author %}
                    <li class="list-group-item">
                        <a class="menu-choice" href="{{ url_for("user.news_edit") }}" target="_parent">写作中心</a>
                    </li>
                    <li class="list-group-item">
                        <a class="menu-choice" href="{{ url_for("user.news_issues") }}" target="main_frame">我的新闻</a>
                    </li>
                {% else %}
                    <li class="list-group-item">
                        <a class="menu-choice" href ="{{ url_for("user.author_register") }}"  target="main_frame">注册作者</a>
                    </li>
                {% endif %}
                <div class="logout-btn">
                    <a class="btn btn-danger" href="{{ url_for("ac.logout") }}">退出登录</a>
                </div>
            </ul>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-9 col-lg-9 iframe-window">
            <div class="embed-responsive embed-responsive-4by3 info-show">
                <iframe class="embed-responsive-item" src="{{ url_for("user.base_info") }}" id="main_frame"
                        name="main_frame"></iframe>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            adjustAvatar();
            windowChange();
            choiceClickBtn();
            logoutBtnAdjust();
        });

        //绑定网页宽度变化
        function windowChange() {
            $(window).resize(function () {
                adjustAvatar();
                logoutBtnAdjust();
            })
        }

        //退出登录按钮样式设置
        function logoutBtnAdjust() {
            let logoutBtn=$(".logout-btn");
            let windowWidth=$(window).width();
            if (windowWidth<369){
                logoutBtn.find("a").text("退出");
            }else {
                logoutBtn.find("a").text("退出登录");
            }
            let liWidth=logoutBtn.siblings('li').innerWidth();
            logoutBtn.find('a').css("width",liWidth);
            //console.log(windowWidth,liWidth);
        }

        //调整头像位置
        function adjustAvatar() {
            let $item = $(".user-menu");
            let $picDiv = $(".user-pic");
            let distance = $item.offset();
            let divWidth = $item.width();
            let toLeft = distance.left;
            let picDivWidth = $picDiv.width();
            let allLeftDistance = (divWidth - picDivWidth) / 2 + toLeft;
            $picDiv.css("left", allLeftDistance);
            //console.log(allLeftDistance);
        }

        //菜单选项点击事件
        function choiceClickBtn() {
            $(".menu-choice").click(function () {
                $(this).parent().siblings().removeClass("select");
                $(this).parent().addClass("select");
                $(this).css("text-decoration", "none");
            })
        }
    </script>
{% endblock %}